version: '3.8'

services:
  database:
    image: postgres_tcc_test:${POSTGRES_IMAGE_VERSION}
    restart: always
    ports:
      - ${POSTGRES_PORTS}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
  app:
    image: flask_tcc:${FLASK_TCC_VERSION}
    ports:
      - 5000:5000
    restart: always
