FROM python:3.10-slim

WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install --upgrade pip
RUN apt-get update \
    && apt-get -y install libpq-dev gcc \
    && pip install psycopg2
RUN pip install -r requirements.txt
COPY . .
WORKDIR /app/src

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--debug"]